\set ON_ERROR_STOP on;


CREATE DATABASE bowls;
CREATE USER app WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD :'app_password';

CREATE USER bowladmin WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD :'admin_password';
GRANT CREATE ON DATABASE bowls TO bowladmin;